my:
  name: 王奕2
  age: 20
  gender: 男
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1911-8-12?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0

  cloud:
    bus: 
      enabled: true
      trace: 
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"